language: java
jdk:
- oraclejdk8
before_install:
- pwd
- echo spring.social.twitter.appId=$appId >> /home/travis/build/ADESQ/TwitterClientWeb/src/main/resources/application.properties
- echo spring.social.twitter.appSecret=$appSecret >> /home/travis/build/ADESQ/TwitterClientWeb/src/main/resources/application.properties
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
after_success:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: AKIAJORCVK25STTSI2YQ
  secret_access_key:
    secure: ZY9XAhBu9+P8MW0qwIRFBQxAtfcl9OrkUOXIUdUBLEQ/vEW3vsEWjcXlRD1HM5F+3WumDpIO7REIPPjt60wrBlvlJpCLH+TbHh8gthgM+PVinvCPRTB3aiUGWtbxZGXBChaSbOXh53i0exqQNpfQFy34dnnMf5A7CIpbxShxJrtFcZDEPo9lERdn0NXHcnyZ8vBts6kr5ydMpFDtkQILej0uu+0FVzVNstWg3v1HEg4t3SpShc09O09yBKJwNwxqensqyHd+QnpN11qomnbzyYXH525lip5n+UbgEUNIVgDKsY7miQmcvbREf8wVB7zg4c9rYGX1Um5DBV2zIP7gmJBP8LReloub7SFjKyeg5Zp1isDRC8aCTLdrA+BngoBEWIAC0SCVkI5AZHDLfQzvmZKWklv/9FEYZYsQ30LjWu8rpeB6yw+HASiOqPXaWn1qPJ5BcKyxIjZDDekyNjhUix3rFk8N/nDXjKH5BZWlK2GnUYM4o4+OwB5WvDSVLv9uUmoHN2aXWNk/efVFpOzLsmhh2YF6GGmRlYMDP9fpHLslz//RE7+XCRCo7K7oH1PQkziDNWBae2p7DL46V2/gGN/I5YD9n2OFvRfn1U6NVWzOiTgMxEB9yrxZGeMxCG0ZIe1hHKfwxgfHdoAWAzzc9IXZEhK/uXhQ8OS3BU02VYM=
  bucket: aws-bucket-twitter-client
  skip_cleanup: true
  region: eu-west-2
  local_dir: dpl_cd_upload
- provider: codedeploy
  access_key_id: AKIAJORCVK25STTSI2YQ
  secret_access_key:
    secure: ZY9XAhBu9+P8MW0qwIRFBQxAtfcl9OrkUOXIUdUBLEQ/vEW3vsEWjcXlRD1HM5F+3WumDpIO7REIPPjt60wrBlvlJpCLH+TbHh8gthgM+PVinvCPRTB3aiUGWtbxZGXBChaSbOXh53i0exqQNpfQFy34dnnMf5A7CIpbxShxJrtFcZDEPo9lERdn0NXHcnyZ8vBts6kr5ydMpFDtkQILej0uu+0FVzVNstWg3v1HEg4t3SpShc09O09yBKJwNwxqensqyHd+QnpN11qomnbzyYXH525lip5n+UbgEUNIVgDKsY7miQmcvbREf8wVB7zg4c9rYGX1Um5DBV2zIP7gmJBP8LReloub7SFjKyeg5Zp1isDRC8aCTLdrA+BngoBEWIAC0SCVkI5AZHDLfQzvmZKWklv/9FEYZYsQ30LjWu8rpeB6yw+HASiOqPXaWn1qPJ5BcKyxIjZDDekyNjhUix3rFk8N/nDXjKH5BZWlK2GnUYM4o4+OwB5WvDSVLv9uUmoHN2aXWNk/efVFpOzLsmhh2YF6GGmRlYMDP9fpHLslz//RE7+XCRCo7K7oH1PQkziDNWBae2p7DL46V2/gGN/I5YD9n2OFvRfn1U6NVWzOiTgMxEB9yrxZGeMxCG0ZIe1hHKfwxgfHdoAWAzzc9IXZEhK/uXhQ8OS3BU02VYM=
  bucket: aws-bucket-twitter-client
  key: latest.zip
  bundel_type: zip
  application: TwitterClient
  deployment_group: TwitterClient
  region: eu-west-2
  on:
    branch: master
env:
  global:
  - secure: b383PU8aWauCWTD5aTfS7jE7fiMtb6o/i8AjCkq5TeKKhtIF3YGGx0BE4ZCo7Ucw+/KuZc/enNK0MSJ+eQj5v4NbAv7DRX8KCLMHOn9ZE6kuPu7PZRPfdICIyBRnIs98X/ec5CS6PjzQDfOCB+9T4+jIz30eqPqfzyzLK70i5aglsZ01R9yd+i+XbUTAdCf1nVADdm6LDT6+E9Vu5JUIFKf96AYmQ6BqWAwAdSZw6LCQVjurLVDybCctvVmFHWyHatjyV/QQfOcOPDxt7cA5byHr/1GwLAYrKxvFk4Cnhcq5o2xqUip3hHiCS5sl/EGoZZTrs94yYVUw9MOcrGLB9ZTV2VECzk12/5ME8vjC183ByBNQ1crXJ+bB78FLVgQ1V+VAS3dfXMqvHqA/2B5GNhuPGM6sdrrPXwslxF75eFhuKlTjrnEq33X1xs6jFL2liodA5wH925BJpQeU7gyLSclx78fdSzXHAF9MhgwpqD31ssgP5DtCOqbNKNJpwMLejdBp1houn1TXAWDTcZLWXE5Eps6I+VHkNySzYFtLCk98qLrE0NpsSiARtJHaVIRiz2XXuAdhe0dyYI/jnBgEfBdivAV+sxOhzhao2VYpQdtMauk6GfPiIPxLccBnV2spxMyg03G9CvZWbWRa/JGSwdcSW12orEXqGYW8PYdWu+Y=
  - secure: ZV9oWvcLYJyOPl2NGXZOkMdRr4ATJBgiTRcA3HBhSs9pVMYWmDF41FdqUJGpvEVDYtswrDturhmo7s0mld4PI7Ae6lP6gM/p0/sPOhN0naZ2JDbOa1TJuzFsWM83PBKWVIp1mwPAaBdAAUmtxlJxeDVH5yZ1snBQ5QB0FDYfQkQqcgDsnKBZgdXXvadMtGZ5NIEj08aI1rYzmUqPNdLu8zz97rjY1m42Rb61pCu0zDHNgwPhBzVi4AK4pehdVgmO5haeZSveh7sG4YOohTbVnj9fecpIgusw6WfRMdu+r5n6ke7HWT00lBz4uq4VMZEdjqCQMnW5ui4a9Ik48oX7Zd+e9utIXo8NitGk18U0ooSp/6fPue4ANgY8DWudqmnws0MzMpUneKXciF4lfGROsZZG/hU4ygyv3o9BrmOWmNQ4QPGR+wXaQRPg84BdEI4MZ3+SnJUnsw4OiwNlTSp2SlxFINHjnJ38opLbclcPRzi+j0x8qdo0GHBjAAl826pcycJ3B/4/wTsDTjcQdUHADwyaqHKzaPkIfwBMNwhGt8zwOe8VlYqdQ5JdalrghY60j5wVwZx5O+pa7+YZ+5LJmfCyu47KQdthttbD0Uw/8s2BKNPjT3EOcrywHBM123zbBuA1zunVYi2QdksWTIUEyjYm79ktJ38Fiaci1mXhpAE=
